export enum CommonType {
  SET_FULLSCREEN = "SET_FULLSCREEN",
  SET_DISPLAY_NUMBER_SYSTEM = "SET_DISPLAY_NUMBER_SYSTEM",
  SET_DISPLAY_UNIT_NUMBER_SYSTEM = "SET_DISPLAY_UNIT_NUMBER_SYSTEM",
}

export const DOWNLOAD_ROW_DATA_REQUESTED = "DOWNLOAD_ROW_DATA_REQUESTED";
export const DOWNLOAD_ROW_DATA_SUCCEEDED = "DOWNLOAD_ROW_DATA_SUCCEEDED";
export const DOWNLOAD_ROW_DATA_FAILED = "DOWNLOAD_ROW_DATA_FAILED";
